### ISSUE TITLE
AR Goggles

### ISSUE THREAD

**Issue by CrackedLua** [Seniorendi/AdvancedPeripherals#138]
### Descripe

So I Made A Heads Up Display Showing Two Players Active Or Not Active And Displaying Their Coords And When I Gave The Goggles To My Friend The Text Was All Spread Out In Random Places.

### Steps to reproduce

1. Make a HUD with lots of text That Looks Good To You 2. Duplicate The Goggles And Give To Someone Else 3. Observe

### Version

0.6r

### Minecraft, Forge and maybe other related mods versions

Forge 36.1.0 Minecraft 1.16.5

### Screenshots or Videos

https://i.alexdevs.pw/7RAx.png
https://drive.google.com/file/d/1YiC1lC1NnkD8XPmprdxO521RNcNHK73k/view?usp=sharing

**Comment by Wojbie** [comment]
This happened on CC Playground server. I will provide crash log tomorrow when I have access to backed.

**Comment by Seniorendi** [comment]
I can confirm this. But this can also happen with different screen sizes. You could try to use `setRelativeMode`, but I don't know if this would help.

> I will provide server crash log tomorrow when I have access to backed.

Does the server crash?

And could you try the latest version?

**Comment by Wojbie** [comment]
> Does the server crash?
> 
> And could you try the latest version?

Server does crash. Crash logs in attachment. Two of them cause CrackedLua decided first time was a fluke ;p

[crash-2021-07-10_13.28.19-server.txt](https://github.com/Seniorendi/AdvancedPeripherals/files/6797518/crash-2021-07-10_13.28.19-server.txt)
[crash-2021-07-10_13.41.57-server.txt](https://github.com/Seniorendi/AdvancedPeripherals/files/6797519/crash-2021-07-10_13.41.57-server.txt)

We are running advancedperipherals-0.6.7b on server. It seems CrackedLua have manualy made modpack instead of using provided one and downloaded wrong AP version. Hope this info i can provide helps.

**Comment by Seniorendi** [comment]
Kay, thank you for the logs

**Comment by SirEndii** [comment]
This should be fixed in 0.7. It was the same issue as #158
