### ISSUE TITLE
RS Bridge: isItemCrafting returns false when item being crafted is a sub-craft

### ISSUE THREAD

**Issue by iconmaster5326** [Seniorendi/AdvancedPeripherals#249]
### Descripe

In a RS network, when you have two items able to be crafted, Item A and Item B, where Item B uses Item A as an ingredient, and you trigger the crafting of item B (which thus invokes item A as a sub-craft), `isItemCrafting` returns `false` on Item A. I would expect it to return `true`, since it is currently being crafted.

### Steps to reproduce

1. Attach a computer to a RS network.
2. On that network, start crafting item B.
3. Call `isItemCrafting` on item A.
4. Check the result.

### Multiplayer?

Yes

### Version

0.7.6r

### Minecraft, Forge and maybe other related mods versions

Forge 36.2.22 Minecraft 1.16.5 RefinedStorage 1.9.16

**Comment by SirEndii** [comment]
I'll let this issue open. But there is currently no way for me to check if an item is an ingredient of one recipe.

**Comment by iconmaster5326** [comment]
So is this an issue with the Refined Storage API not exposing the correct information? If so, I can refer this issue to Refined Storage's issue tracker.

**Comment by SirEndii** [comment]
This is not really an issue
But It does not seem that RS has a way in their api to see if an ingredient is currently crafting.
But sure, you can make an issue at the Refined Storage's issue tracker.

**Comment by cn-ml** [comment]
I am uncertain if this is even expected behaviour. I just created a discord bot interface using the RS bridge on our server and when i try autocrafting with the bot I need to know if the item is currently being created. If it was checking if the item is part of a recipe being crafted, then that would mean that - when crafting is finished - the item i was checking was not created (i.e. was directly used).

**Comment by SirEndii** [comment]
I'll close this now.
Ingredients will not be caught by `isItemCrafting`. Since this is also not possible with the current state of the RS Api.
Returning true for crafting ingredients could also lead to confusion if a user wants to know if a real item is crafting, but it's just true cause of an ingredient.
