### ISSUE TITLE
meBridge.craftItem(table) returns true always

### ISSUE THREAD

**Issue by RedStoner** [Seniorendi/AdvancedPeripherals#323]
### Descripe

When calling meBridge.craftItem({name=v.name, count=v.craftCount}), it returns true no matter if the craft was successfull or not. Documentation shows that it should return a table ()

Versions of mods/forge -
advancedperipherals-1.18.2-0.7.15b.jar
cc-tweaked-1.18.2-1.100.8.jar
forge - 40.1.60
Minecraft 1.18.2

Playing ATM 7 v0.4.22

### Steps to reproduce

Setup AE to have a recipe that is missing ingredients to craft.
Call craftItem using meBridge.
Notice it returns true

### Multiplayer?

Yes

### Version

1.18.2-0.7.15b

### Minecraft, Forge and maybe other related mods versions

forge - 40.1.60 Minecraft 1.18.2

**Comment by SirEndii** [comment]
The `craftItem` method returns now true if the job has been started and false if the item is unavailable

I only return true if the craft job has been started because the start of the job and the calculation does not run at the same time.
I originally had in mind to fire a event `crafting` if the crafting finished or the job aborted because of any reason. This *should* work, but I didn't tested the system since I created the me bridge. 
I'll later rework return types of *all* of our methods, this will then also include the me bridge and the crafting event.
