### ISSUE TITLE
The wiki (docs.srendi.de) is down

### ISSUE THREAD

**Issue by Zvitorep** [Seniorendi/AdvancedPeripherals#328]
### Descripe

The official wiki for the mod is down, no other sources exist on the internet that document the mod. Archive.org has a handful of pages that don't provide a pleasant experience.

### Steps to reproduce

Visit docs.srendi.de

### Multiplayer?

No

### Version

1.18.2-0.7.16b (Latest 1.18)

### Minecraft, Forge and maybe other related mods versions

Firefox 101

**Comment by UnhappyCodings** [comment]
Hey Urufusan, the domain srendi.de is currently unavailable for the next 30 days. You can use https://peaceful-nobel-03befe.netlify.app/ instead.

Have a nice day!

**Comment by Sakata-MC** [comment]
Please update curseforge and wiki page here for now - might save you some headache. I almost posted an issue until I recalled removing the is:open tag...

**Comment by SirEndii** [comment]
I updated the wiki on the right and the discord link is updated 
![image](https://user-images.githubusercontent.com/67484093/188456377-4eeb9877-ab5a-43d7-9f6a-46affcf5d752.png)

Since I can register the domain again in 4 days, I don't want to change the urls 
But yeah, I should've changed all the urls at the beginning

If you don't want to miss future updates and announcements like these, you can join our [discord server](https://discord.com/invite/QuF3hWDtWC)!
