### ISSUE TITLE
Chunks loaded by chunky turtles are not loaded upon reloading the world

### ISSUE THREAD

**Issue by UpsideDownFoxxo** [Seniorendi/AdvancedPeripherals#557]
### Describe

When a chunky turtle moves out of render distance and is the only thing loading itself, reloading the world will not re-load the turtle.

### Steps to reproduce

1. Place a chunky chatty turtle outside of the spawn-chunks.
2. Insert into `startup.lua`:
```lua
local chatBox = peripheral.find("chatBox",peripheral.wrap)
while true do
chatBox.sendMessage("hi")
end
```
3. Leave the chunks so the turtle is out of render distance
4. Reload the world

The turtle will no longer spam the chat, and only reactivate when loaded by external means.

### Multiplayer?

No

### Version

1.18.2-0.7.31r (Latest 1.18.2)

### Minecraft, Forge and maybe other related mods versions

Forge 40.2.8 Minecraft 1.18.2

**Comment by SirEndii** [comment]
Greetings

The issue here is, that the chunky turtle does not tick when it's not loaded. And if it does not tick, it does not load chunks

A partial workaround is to place third party chunk loads on the way, but that's highly inefficient
I will try to fix this somehow in AP by remembering the ID of the turtle and then after a server/world restart trying to load that chunk of the turtle. That should in theory start the peripheral of the turtle, which should start loading chunks

**Comment by UpsideDownFoxxo** [comment]
Yea, the problem I'm experiencing is on unexpected restarts (like crashes). I can plan for saving my world and safely return my turtles, but when the system crashes I can't.

**Comment by zyxkad** [comment]
Reopen for release @SirEndii
