### ISSUE TITLE
Server crash with MineColonies when trying to call getWorkOrderResources

### ISSUE THREAD

**Issue by Fureniku** [Seniorendi/AdvancedPeripherals#558]
### Describe

When executing the following code, the server crashes with the attached crash log.

``` lua
local wo1 = colony.getWorkOrderResources(257) --257 is a valid current order, but I wouldn't expect an invalid one to crash either
for i = 1, #wo1 do
  print(wo1.displayName .. " " .. wo1.neded .. " " .. wo1.status)
end
```

Using MineColonies 1.20.1-1.1.471-BETA, CC:Tweaked-1.20.1-forge-1.109.5 and AP 1.20.1-0.7.36r

Worth noting the version dropdown does list an AP 0.7.37r, but this doesn't seem to be available on CurseForge - so apologies if this is already fixed.

### Steps to reproduce

1. Set up a computer with a colony integrator
2. Run the above code
3. Cry when the server crashes :'( 

### Multiplayer?

Yes

### Version

1.20.1-0.7.36r

### Minecraft, Forge and maybe other related mods versions

Forge 47.2.0 for Minecraft 1.20.1

### Screenshots or Videos

N/A

### Crashlog/log

https://pastebin.com/QFBgdB0M

**Comment by SirEndii** [comment]
Damn minecolonies api changes

**Comment by SirEndii** [comment]
Fixed in dev using the currently latest available minecolonies version

Feel free to try the snapshots
- [1.19.2-0.7.34r Snapshot](https://mvn.intelligence-modding.de/#/Intelligence/de/srendi/advancedperipherals/advancedperipherals-snapshots/1.19.2-0.7.34r-SNAPSHOT-209)
- [1.20.1-0.7.38r Snapshot](https://mvn.intelligence-modding.de/#/Intelligence/de/srendi/advancedperipherals/advancedperipherals-snapshots/1.20.1-0.7.38r-SNAPSHOT-210)
