### ISSUE TITLE
You are not attached to this computer

### ISSUE THREAD

**Issue by Did-Nikole** [Seniorendi/AdvancedPeripherals#572]
### Describe

[01Apr2024 22:25:44.701] [Server thread/ERROR] [dan200.computercraft.core.computer.LuaContext/COMPUTER_ERROR.JAVA]: Error running task dan200.computercraft.api.peripheral.NotAttachedException: You are not attached to this computer

Accessing chest with chest.pushItems(peripheral.getName(storage), slot) while in use by turtle/human causes program running on computer to crash

I am running the DW20, 1.20 mod pack from FTB, only change made was to disable "NoMoreWanderer" mod.

### Steps to reproduce

1) Place Modem as block, add computer to top, chest behind, turtle facing chest
2) constantly add items to chest with computer in a loop
3) When turtle/player accesses chest it becomes unavailable to the computer, causing it to crash.

### Multiplayer?

No

### Version

1.20.1-0.7.35b

### Minecraft, Forge and maybe other related mods versions

NeoForge 47.1.84

### Crashlog/log

https://pastebin.com/RRyhf6r5

**Comment by SirEndii** [comment]
Why do you think this is an Issue with AP?
I don't see anything related to AP

**Comment by SirEdvin** [comment]
So, it this this issue is related to [Peripheralium](https://github.com/SirEdvin/Peripheralium) again (!). I would try to get back together and finally fix some bugs that covered it :( 

For now you can just disable Generic inventory peripheral from UPW entirely via `enableGenericInventory` function, this would restore default CC:T inventory capabilities, or you can just add `peripheralworks:ignore` block tag to chest to achieve same results just for chests.

I would move this issue to [Peripheralium](https://github.com/SirEdvin/Peripheralium) repository.
