### ISSUE TITLE
Inventory Manager is not compatible with Computercraft: Tweaked's relative directions.

### ISSUE THREAD

**Issue by OneTwoMint** [Seniorendi/AdvancedPeripherals#89]
The relative directions from Computercraft: Tweaked, such as "top", "bottom", "back", and "front" don't work as references to inventory blocks, returning `Java Exception Thrown: java.lang.IllegalArgumentException: No enum constant net.minecraft.util.direction.BACK` in the case of referring to an inventory placed behind the Inventory Manager using "back".

**Comment by Seniorendi** [comment]
The inventory manager uses cardinal points as the direction argument. Like "NORTH", "UP", "DOWN", ... .

**Comment by OneTwoMint** [comment]
Why, though? Most things in Computercraft: Tweaked use the relative directions as far as I know, and even the Redstone Integrator is compatible with them. It seems strange that the Inventory Manager would have this limitation.

**Comment by Seniorendi** [comment]
Yes, i approve your message. I will add the cc direction integration to every block soon.

**Comment by RGFTheCoder** [comment]
this also doesn't work with named peripherals (like "minecraft:chest_0") when connecting by cable

**Comment by RGFTheCoder** [comment]
@Seniorendi

**Comment by Seniorendi** [comment]
> this also doesn't work with named peripherals (like "minecraft:chest_0") when connecting by cable

What does not work?

**Comment by RGFTheCoder** [comment]
If you use the cables and wired modems, one cannot do `manager.addItemToPlayer("minecraft:chest_0", 63, "minecraft:dirt")` when that chest is connected to the cable. This is allowed on the normal inventory API on cc:tweaked as long as both inventories are wired. Trying to move items from a cabled chest to a cabled inventory manager causes a Java error because its not part of the enum of options, even though it should be able to be any connected inventory. @Seniorendi

**Comment by RGFTheCoder** [comment]
Also, it would be very cool if the inventory manager implemented the same api as the cctweaked inventory api as it would allow polymorphic code to utilize both

**Comment by RGFTheCoder** [comment]
This could also be done to the RS and AE bridges as they have similar import/export item functions which are similar to push/pull items from cct
